language: kotlin
sudo: required
dist: trusty

jdk:
- oraclejdk8

stages:
  - name: build

env:
  global:
  - JAVA_OPTS="-Xms512m -Xmx1024m"

jobs:
  include:
  - stage: build
    name: "Compile and test"
    script: ./gradlew clean build :arrow-benchmarks-fx:jmhClasses
    deploy:
      provider: script
      script: ./deploy-scripts/deploy.sh
      skip_cleanup: true
      on:
        branch: master
  - name: "Generate docs"
    before_install:
      - gem update --system
      - gem install bundler
    install:
      - bundle install --gemfile modules/docs/arrow-docs/Gemfile --path vendor/bundle
    script: |
      ./gradlew dokka
      ./gradlew :arrow-docs:runAnk
      export BUNDLE_GEMFILE=modules/docs/arrow-docs/Gemfile
      travis_wait bundle exec jekyll build -s modules/docs/arrow-docs/build/site -d modules/docs/arrow-docs/build/_site
    deploy:
      provider: gcs
      access_key_id: ${GCLOUD_ACCESS_KEY_ID}
      secret_access_key: ${GCLOUD_SECRET_ACCESS_KEY}
      bucket: second.fortysevendegrees.com
      skip_cleanup: true
      acl: public-read
      local-dir: modules/docs/arrow-docs/build/site/*
